### ISSUE TITLE
Make go forever an actual button

### ISSUE THREAD

**Issue by qiemem** [arthurhjorth/LevelSpaceXWGUI#13]
I'm doing this right now

**Comment by qiemem** [comment]
Ack, nevermind, the UI appears to stop responding... well sort of. Swing elements still activate, but things don't update properly. Pressing the button again does not run its command. I wonder if this is because it's doing so much swing work.

I don't get it. The button spawns a concurrent job asynchronously just like the checkbox. Basing the button code off this: https://gist.github.com/qiemem/582e8393ca6003171ab5

**Comment by arthurhjorth** [comment]
done by @qiemem
