### ISSUE TITLE
Get rid of number prefixes

### ISSUE THREAD

**Issue by qiemem** [arthurhjorth/LevelSpaceXWGUI#17]
Depends on qiemem/LSWidgets#5

**Comment by arthurhjorth** [comment]
working on this now

**Comment by arthurhjorth** [comment]
3f5115e5d4e75d0e5ef83094da783d5997e46767 and 85913fd33b2fdabe19ddf7c482ea05f8f19c264d fixed this, though becasue of the JCOmponents in the widget, we can't entirely get rid of the number prefixes.
