### ISSUE TITLE
bug:  In one use-path, SETUP not working in model 0

### ISSUE THREAD

**Issue by cbradyatinquire** [arthurhjorth/LevelSpaceXWGUI#33]
steps to reproduce:
1) load the nlogo file 
1a) DO NOT RUN ANY SETUP BLOCKS BEFORE STEP 2
2) Load New Model, with another model
3) create SETUP blocks to run setup in each model.
4) run them.  Setup will be run only in the New model that was opened in step 2

interestingly, if you create  a setup block before doing Load New Model, it WILL run setup in model 0.  Moreover, the bug will NOT appear after this.

But if you don't run any setup blocks before loading a Model 1, then after loading,   both 0:setup and 1:setup will actually run 1:setup

**Comment by qiemem** [comment]
Is this still not working?

**Comment by cbradyatinquire** [comment]
(this was fixed i think with arthur's change the day after i reported it)
