### ISSUE TITLE
Name of LevelSpace system shouldn't be "Model"

### ISSUE THREAD

**Issue by cbradyatinquire** [arthurhjorth/LevelSpaceXWGUI#43]
In the UI, Save and Load of LevelSpace system uses the term "Model" (same term as used for NetLogo models, in button above).

I'd suggest using the term "LevelSpace System" (as a System of [NetLogo] Models)

But, wanted to get feedback/thoughts rather than just making this change.

**Comment by mrerrormessage** [comment]
@qiemem , I remember discussing names for this with you (there may have been other people there as well) - I think metamodel and metaverse came up (not that I believe those are the best possible names). What were other suggestions?

**Comment by arthurhjorth** [comment]
fixed 6a957acc97c27375e13dc2c202696e574572f046
