### ISSUE TITLE
If you overwrite (save on an existing) relationship with args to one that doesn't, it messes up

### ISSUE THREAD

**Issue by arthurhjorth** [arthurhjorth/LevelSpaceXWGUI#59]

**Comment by arthurhjorth** [comment]
My theory is that it is a problem with the widget. WHen you save, it doens't clear the selected arguments, and so we try to save a relationship with a command or agent that doesn't take args, but still try to pass them args.

**Comment by qiemem** [comment]
Pretty close. xw caches properties (sort of). We were signaling updates when available items change for individual arguments. But when they're _all_ removed, none of the individual available items changed (just the arguments themselves were removed). Anyway, fixed.
