### ISSUE TITLE
relationship arguments not saved

### ISSUE THREAD

**Issue by qiemem** [arthurhjorth/LevelSpaceXWGUI#8]
This is true for both agentsets and commands. This:

![image](https://cloud.githubusercontent.com/assets/28215/7335159/5213f7dc-eb71-11e4-89f3-e6f17f1bd8c0.png)

becomes this:

![image](https://cloud.githubusercontent.com/assets/28215/7335161/5df3a5b6-eb71-11e4-873a-d7778718ecbb.png)

**Comment by arthurhjorth** [comment]
Command args are saved, but not updated in the widget when redrawn. Agent args seem not to be saved at all.
